### ISSUE TITLE
Font Validation report

### ISSUE THREAD

**Issue by thlinard** [cyrealtype/Artifika#1]
See https://github.com/google/fonts/issues/1305

**Comment by alexeiva** [comment]
Please check the new [ttf](https://github.com/cyrealtype/Artifika/tree/master/fonts/ttf) in this repo, reopen if issue is not fixed

**Comment by thlinard** [comment]
Indeed! Issue solved! Thank you very much!

**Comment by alexeiva** [comment]
thank you, I will do the same for others fonts, and then request a push altogether.
